### ISSUE TITLE
Support `aws-lc` for default `rustls`

### ISSUE THREAD

**Issue by clux** [clux/muslrust#141]
https://github.com/aws/aws-lc is needed for default builds of [rustls 0.23](https://github.com/rustls/rustls/releases/tag/v%2F0.23.0).

this is seen in [their features](https://github.com/rustls/rustls/blob/9ef2150472a9b3363bc081870685fe4c26404715/rustls/Cargo.toml#L18-L37)
and [blog post](https://www.memorysafety.org/blog/rustls-with-aws-crypto-back-end-and-fips/)

spotted via a [test error a few days ago](https://github.com/clux/muslrust/actions/runs/8100786399/job/22139536117#step:11:382):

```
   Compiling ring v0.17.8
   Compiling aws-lc-sys v0.13.2
   Compiling ring v0.16.20
error: failed to run custom build command for `aws-lc-sys v0.13.2`

Caused by:
  process didn't exit successfully: `/volume/target/debug/build/aws-lc-sys-095b332bc7a90d49/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=use_bindgen_generated

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.13.2/builder/main.rs:286:5:
  aws-lc-sys build failed. Please enable the 'bindgen' feature on aws-lc-rs or aws-lc-sys
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
     2: build_script_main::main
               at ./builder/main.rs:286:5
     3: core::ops::function::FnOnce::call_once
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: Recipe `_t` failed on line 27 with exit code 101
Error: Process completed with exit code 101.
```

judging by their issues it should be possible: https://github.com/aws/aws-lc/issues/384
instructions look [simple enough](https://github.com/aws/aws-lc?tab=readme-ov-file#quickstart-for-amazon-linux-2)

**Comment by clux** [comment]
probably more urgent now that the future of ring is being called into question. e.g. https://github.com/kube-rs/kube/issues/1699

will have an initial look at it
